version: '3'

services:
  seafile-client:
    restart: always
    image: snegov/seafile-client
    environment:
      - LIBRARY_ID="79867cbf-2944-488d-9105-859463ecdf9e:test_library"
      - SERVER_HOST=seafile.example.com
      - USERNAME=user
      - PASSWORD=password
      - SEAFILE_UID=1000
      - SEAFILE_GID=100
    hostname: docker-seafcli
    volumes:
      - seafile-data:/seafile-client/seafile-data
      - /home/johndow/seafile:/data
    container_name: seafile-client

volumes:
  seafile-data:
