version: '3'
services:
  seafile-client:
    restart: always
    build: .
    container_name: seafile-client
    environment:
      - LIBRARY_ID=<your-library-id-here>
      - SERVER_URL=<server-url>
      - SERVER_PORT=<server-port>
      - USERNAME=<username>
      - PASSWORD=<password>
      - DATA_DIR=<directory-path-to-sync>
      - SEAFILE_UID=<your_uid>
      - SEAFILE_GID=<your_gid>
    volumes:
      - <host-volume-path>:<directory-path-to-sync>
